name: golang-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test

      - name: Vet
        run: |
          go vet ./...
  # Задание проверяет код на соответствие стилю и отсутствие логических ошибок
  lint:
    # Задание "lint" зависит от заданий "tests" и "tests-race" и будет выполнено после них
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      # Используется действие "golangci/golangci-lint-action@v3", которое запускает линтер. Он проверит код на соответствие стилю и отсутствие логических ошибок
      - uses: golangci/golangci-lint-action@v3

  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [test,lint]
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: epicpt/final-project-12th-workflow

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
# PR for yandex practicum